id: P007092
initial_creation_type: ocr
source_metadata:
  id: bdr:W25274
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད
  author: ''
  volumes:
    2346ab546d1344b3a48c9ed5d0cda223:
      image_group_id: I1PD96715
      title: ''
      volume_number: 1
      total_pages: 140
ebook_metadata:
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད
  author: ''
  sku: P007092
  cover: cover.jpg
  layers:
  - pagination
