id: opecha:P007092
initial_creation_type: ocr
source_metadata:
  id: bdr:W25274
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད
  volume:
    99aa94fdaf12494bb55b90652a79213e:
      image_group_id: I1PD96715
      title: Volume 1 of sbas yul 'bras mo ljongs kyi gnas yig phan yon bcas pa ngo
        mtshar gter mdzod
      volume_number: 1
      total_pages: 140
  author: ''
ebook_metadata:
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད
  author: ''
  sku: P007092
  cover: cover.jpg
  layers:
  - pagination
