id: IFE45BD32
legacy_id: P007092
ocr_import_info:
  bdrc_scan_id: W25274
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T23:47:23'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T06:12:16.902791+00:00'
last_modified: 2022-09-02 14:12:25.675931
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W25274
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW25274
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད།
  author: ལྷ་བཙུན་འགྱུར་མེད་འཇིགས་བྲལ་བསྟན་འཛིན་དཔའ་བོ།
statistics:
  ocr_word_mean_confidence_index: 0.5304739403073373
  ocr_word_median_confidence_index: 0.5099999904632568
quality: null
bases:
  I1PD96715:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1PD96715
      total_pages: 140
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1PD96715.txt
    statistics:
      ocr_word_median_confidence_index: 0.5099999904632568
      ocr_word_mean_confidence_index: 0.5304739403073373
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
