id: IFE45BD32
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:48:18+00:00'
last_modified: '2022-06-09T04:47:36.419415+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W25274
  title: སྦས་ཡུལ་འབྲས་མོ་ལྗོངས་ཀྱི་གནས་ཡིག་ཕན་ཡོན་བཅས་པ་ངོ་མཚར་གཏེར་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A49E:
      image_group_id: I1PD96715
      title: Volume 1 of sbas yul 'bras mo ljongs kyi gnas yig phan yon bcas pa ngo
        mtshar gter mdzod
      total_pages: 140
      order: 1
      base_file: A49E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
